Feature/Adding BaseEntity and README.md update
Ramchy-J/OT-Restaurante pull request #8
Opened 2024-03-07 03:05 UTC by Ramchy-J

-Adding BaseEntity
-Updating readme

2024-03-08 02:14 UTC, eapg commented on entities/Base.java
> +
Add `createdBy` and `updatedBy`

2024-03-08 02:15 UTC, eapg commented on entities/Base.java
> +    private String name;
Remove this property as this entity will be instantiate by all the others entities and not all of then need `name` property.

2024-03-08 02:22 UTC, eapg commented on entities/Base.java
> +    private Date createdDate;
Use `Instant` instead of `Date`

2024-03-08 02:24 UTC, eapg commented on entities/Base.java
> +    private Integer id;
Use `Long` instead of `Integer`. As restaurant entities should grown in a level greater than the maximum value of an `Integer`

2024-03-11 13:57 UTC, eapg commented on entities/Base.java
> +    private String createdBy;
Change the type to `Long` as the `createdBy` and `updatedBy` will be ids.

2024-03-19 20:22 UTC, reynoldmorel approved these changes

2024-03-19 20:23 UTC, reynoldmorel requested changes

2024-03-19 20:23 UTC, reynoldmorel commented on constants/Status.java
> +    DELIVERED
you should include `ACTIVE and DELETED` as well

2024-03-20 18:03 UTC, Ramchy-J commented on entities/Base.java
> +
done

2024-03-20 18:03 UTC, Ramchy-J commented on entities/Base.java
> +    private String name;
done

2024-03-20 18:03 UTC, Ramchy-J commented on entities/Base.java
> +    private Date createdDate;
done

2024-03-20 18:03 UTC, Ramchy-J commented on entities/Base.java
> +    private Integer id;
done

2024-03-20 18:03 UTC, Ramchy-J commented on entities/Base.java
> +    private String createdBy;
done

2024-03-20 18:03 UTC, Ramchy-J commented on constants/Status.java
> +    DELIVERED
done

2024-03-21 11:47 UTC, reynoldmorel approved these changes

2024-03-21 21:55 UTC, merged